- config/BarConfig.qml
Battery Width Property Being set to:
```
property int batteryWidth: 200`
```
is too cramped for the details to display properly.
With Battery Width Adjusted to 250
```
property int batteryWidth: 250
```
now this will allow the contents to show properly while hovering in battery section.
> Battery Default Width Issue

- services/SystemUsage.qml
This PR enables the CPU temperature to be retrieved depending on the driver. Actually some CPUs are not supported from the code.
**Added**: k10temp-pci-00c3 driver family support
Using a simple non capturing group in regex to catch either `Package id` or `Tdie` line in sensors output.
As some AMD CPUs have no Tdie line in sensors output, depending on the model, we can fallback to Tctl instead. (see #138 for instance).
Use Tctl as a fallback only if Tdie not existing for AMD, as Tdie is preferred and more accurate. Tctl is using an offset on the temperature on some models.
Based on: https://www.hwinfo.com/forum/threads/cpu-temp-sensors-explanation.5597/
Tested on a fresh local installation, working.
sensors output:
```
◄ 0s ◎ sensors …
```
> refactor: CPU temperature regex retrieval multivendor

- services/SystemUsage.qml
As the variable cpuTemp can now be used later in the if block for the fallback, need to change the declaration so that the variable is unique and used in two different blocks.
Const will redeclare it.. My bad on this
Tested to be sure the fallback works, with setting a bad value in the previous block to get sure to use the fallback. Working
I need a coffee..
> [typo] cpuTemp bad declaration

- README.md
- config/DashboardConfig.qml
- modules/dashboard/dash/Weather.qml
- modules/lock/WeatherInfo.qml
- services/Weather.qml
1. Added `useFahrenheit` setting to DashboardConfig.qml (I realize this also applies to the lockscreen, but the `weatherLocation` was here so I figured I'd keep it consistent)
2. Changed Weather service to use the `useFahrenheit` config
3. Changed Weather service's `temperature` to be a string including the unit
4. Updated Modules to directly use Weather's `temperature` string
I tested this locally, seems to be working great.
I couldn't any info on making PRs to this repo, let me know if you want a different format or anything else.
> feat: Added Fahrenheit to Weather Service

- services/Brightness.qml
This adds support to the Apple Studio Display monitor brightness control.
I tested without `asdbctl` installed as well to make sure I am not breaking anything.
I'm new to `quickshell` and `qml` so happy to adjust if anything is incorrect or not following best practice.
> chore: add studio display support

- config/BarConfig.qml
- modules/bar/popouts/Network.qml
- services/Network.qml
This PR improves the network popout based on the bluetooth popout. Currently, I've only implemented it for saved networks, I'm not sure about how the UI should look like for password popup.
- Added `networkWidth: 320` to `BarConfig.qml` for consistent sizing
- Network popout now follows a similar UI as the Bluetooth popout
- Network service now has additional functions and variables to rescan, connect, disconnect, enable/disable and toggle wifi
- Added `wifiEnabled` and `scanning` properties
- Duplicate SSIDs are not displayed (my home has multiple repeated networks with name SSID)
Two further improvements required:
> feat: improve network popout

- README.md
- config/SessionConfig.qml
- modules/lock/Buttons.qml
- modules/session/Content.qml
This PR adds the ability to customize the commands that the session/lockscreen buttons execute in shell.json.
I for example don't use hibernate, so I changed it to systemctl suspend on my machine. LMK if this is okay. 
I could also seperate the config for the commands to lock and session, but I will leave the decision up to you boss.
> session/lock: Add custom session/lock menu button commands

- README.md
- config/SessionConfig.qml
- modules/session/Content.qml
This adds the same keybinds I made for the launcher to the session menu. That also includes the Tab key. 
There are some decisions I made here (and for launcher), that may need to be discussed. For example that the Tab-Key navigation could also be enable by default, without enabling vimKeybinds, but I will leave it like this, to change your defaults as little as possible. 
I am happy enough if these changes make it upstream at all, so hmu if something needs changing.
> session: add optional vim-like keybinds

- README.md
- config/BarConfig.qml
- config/ServiceConfig.qml
- modules/background/DesktopClock.qml
- modules/bar/components/Clock.qml
- modules/dashboard/dash/DateTime.qml
- modules/lock/Clock.qml
Add a simple option to config to use 12 hour clock, for the americans.
Here's what it looks like:
The functionality is opt-in and existing setups will continue using 24h format unless they change their settings
closes: https://github.com/caelestia-dots/shell/issues/261 
closes: https://github.com/caelestia-dots/shell/issues/207
> config: respect user locale for twelve hour clock, temperature

- modules/bar/components/StatusIcons.qml
Very small PR to use the "bluetooth connected" icon from material icons when a bluetooth device is connected
On my local machine I will be using this instead of the list of icons for each device to reduce a bit of clutter in the sidebar. I think this list is not needed with this new icon and the ability to see connected devices in the bluetooth panel.
I left the removal of the icon list out on purpose in this PR in case you still want to have it. If you think we can remove the icon list I can add it to this PR as well
> bar: add bluetooth connected icon state

- modules/launcher/WallpaperList.qml
Small fix that allows you to use the wallpaper selector when you have exactly two wallpapers. Here's what it looks like when you have two wallpapers present (same as before)
I initially wanted to go for an infinite loop where the wallpapers would be displayed as `list[0], list[1], list[0]` but it gave me giant headache. This way, the styling is not perfect but at least the functionality works
> launcher: allow wallpaper switch when exactly 2 wallpapers present

- services/Wallpapers.qml
useful when you have wallpapers managed by a dotfiles manager, for example
> internal: allow symlinked wallpaper directory

- flake.nix
- nix/default.nix
- nix/hm-module.nix
This PR adds a home manager module and allow easily configuring `.config/caelestia/shell.json` option using Nix language. This module also creates a systemd user service which starts Caelestia shell after Hyprland.
With the growing of the project its good to have a home manager module for Nix users.
```nix
programs.caelestia = {
enable = true;
settings = {
bar.status = {
showBattery = false;
};
paths.wallpaperDir = "~/Images";
};
};
```
This module adds only `caelestia-shell` to PATH, if one wants to add the `caelestia` (CLI) too:
```nix
programs.caelestia.cli.enable = true;
```
Also allows a user to configure an `extraConfig` in the case they don't want to configure options using nix.
~~At the time of writing this, the systemd service only works for Hyprland, but it's not hard to extend …
> nix: add home manager module

- nix/hm-module.nix
This PR fixes #390 for people that use the `home-manager`-module of this project. Have a look at the issue for why we chose to export the environment variable instead of using the CLI to start the shell.
> nix: fix missing icons in hm-module

- README.md
- config/OsdConfig.qml
- modules/osd/Content.qml
An option to disable the brightness slider for desktop users.
The brightness slider doesn’t really work on desktops and just takes up space, so turning it off for desktop users would keep the interface cleaner and less confusing.
> Added option to disable brightness slider

- CMakeLists.txt
- assets/cpp/CMakeLists.txt
- flake.nix
- nix/default.nix
- plugin/CMakeLists.txt
With the latest changes (d65fb180ad5ee41049b9d0f9a962901524636b6a) the caelestia plugin was added, and this broke the nix develop environment (no more `qs -p .`, it fails with missing module) since the quickshell package exposed to that environment is not wrapped with `wrapQtAppsHook` and the plugin. 
- fixes this issue wrapping separately the quickshell into a package and adding it to `buildInputs`. 
- use `caelestiaEnv` to automatically add env vars to package and dev shell.
- uneeded binaries were removed from PATH
- removed old `gcc` dependency from caelestia-shell `nativeBuildInputs`
> nix: better dev shell + refactor

- README.md
- nix/hm-module.nix
Modify the hm module to add an option to disable the systemd service for those don't like it or don't want to start it using systemd at all. Defaulting to true so it doesn't break current behavior.
Not exactly a fix, but may help #512
> nix/hm: add option to disable systemd service

- services/Brightness.qml
Previously, monitor detection was based on the model name. This caused issues when using multiple monitors with the same model name: changing the brightness of either would only affect one of them.  
Detection is now based on the connector, ensuring that each monitor can be controlled individually.
> fix(brightness): detect monitors by connector instead of model

- README.md
- nix/hm-module.nix
This PR will enable systemd services to start automatically only in specific desktop environments, Like other services ([waybar](https://github.com/NixOS/nixpkgs/blob/7e012249499ba8c991a1b56b5af3454d3a496548/nixos/modules/programs/wayland/waybar.nix#L19) [others](https://mynixos.com/search?q=systemdTarget)).
> nix: add systemd.target in home-manager

- config/BarConfig.qml
- modules/bar/components/workspaces/SpecialWorkspaces.qml
Because special workspaces already might have icons relating to the window inside it, it's redundant to also show the window.
> bar(workspaces): different `showWindows` option for special ws

- modules/dashboard/Dash.qml
- modules/dashboard/Wrapper.qml
- modules/dashboard/dash/Calendar.qml
- modules/dashboard/dash/DateTime.qml
Adds the month/year to the top of the calendar, and provides buttons for paging. Also removed day/month from time panel, and added highlighting to weekends
> dashboard: add month/year and paging to calendar

- README.md
- nix/hm-module.nix
This PR renames `programs.caelestia.environment` to `programs.caelestia.systemd.environment` in hm module without breaking current behavior (may be fully removed in future). Since this environment is exclusive of the systemd service, so does make more sense to define it in this place. 
Also changes the default systemd target to `config.wayland.systemd.target` since this is a home manager convention for wayland services, allowing the user change that option and modify the target of all wayland systemd services.
And it does a refactor in the readme in a way the configuring section be more clear.
> nix/hm & readme: move environment to systemd.environment + refactor

- nix/default.nix
libcava failing with fftw3.h not found, giving errors in the build. It seems to me fftw had to be in libcava's propagatedBuildInputs but anyway this is a fix
> nix: fix build error with libcava

- modules/bar/components/StatusIcons.qml
- modules/lock/Fetch.qml
previously the logic used `UPower.onBattery`. I changed it to use `UPower.displayDevice.state === 2`.
on my laptop (ASUS G16 Zephyrus), `UPower.onBattery` would return false even after unplugging the charger, which means that the battery icon would still be the "charging" icon after unplugging.
using the explicit `displayDevice.state` enum fixes this for both the system tray and the lock screen fetch logic
docs:
[UPower.displayDevice.state](https://quickshell.org/docs/master/types/Quickshell.Services.UPower/UPowerDeviceState/)
> fix: Battery charging logic for Tray and Lock
